#!/bin/bash

# Setup Docker environment. If '/certs' is mounted then use SSL
host=$http://54.175.42.138:8080


# Clone repo
repo=$1
git clone https://github.com/${repo}.git

# Extract last part and cd into it
parts=(${repo//\// })
cd ${parts[1]}

# Run maven with the rest of the commands
shift
/maven/bin/mvn $*
