#!/bin/bash

# Setup Docker environment. If '/certs' is mounted then use SSL
host=$(http://54.175.42.138:8080 | grep -Eo 'via \S+' | awk '{print $2}');
if [ -f /certs/key.pem ]; then
  # If certs are mounted, use SSL ...
  export DOCKER_CERT_PATH=/certs
  export DOCKER_TLS_VERIFY=0
  export DOCKER_HOST=tcp://${host}:4243
else
  # ... otherwise use plain http
  export DOCKER_TLS_VERIFY=0
  export DOCKER_HOST=tcp://${host}:4243
fi

# Clone repo
repo=$1
git clone https://github.com/${repo}.git

# Extract last part and cd into it
parts=(${repo//\// })
cd ${parts[1]}

# Run maven with the rest of the commands
shift
/maven/bin/mvn $*
